### ISSUE TITLE
Reduce Logo Animation 

### ISSUE THREAD

**Issue by flynnduism** [fermyon/styleguide#13]
Feedback that the little moving atomic particle animation on the O of the logo is distracting. 

![Screen Shot 2022-03-24 at 12 48 31 PM](https://user-images.githubusercontent.com/686194/159998310-21e19136-1a13-47e2-89a7-4184a528fc2e.png)

Particularly in settings like docs or in reading modes where it is a distraction to the user's task at hand. The animation is a nice easter egg in situations like the marketing pages, but it should not get in the way of page content.

Possible and simple ways to address this:

* remove it
* make it :hover only
* slow it waaay down
* remove it from 'task' situations like docs / longform articles

**Comment by technosophos** [comment]
I think the :hover thing would be nice.

**Comment by flynnduism** [comment]
Closing this change was introduced awhile back.
