### ISSUE TITLE
Tables demo looks wierd in dark mode

### ISSUE THREAD

**Issue by Megrax** [fermyon/styleguide#20]
## light mode
<img width="837" alt="image" src="https://user-images.githubusercontent.com/56376387/161391632-ba140f28-638a-4e44-a723-47d25ff4ddd9.png">

## dark mode
<img width="841" alt="image" src="https://user-images.githubusercontent.com/56376387/161391624-818f39f0-86b6-4a5a-8ebb-0dad83fa54ab.png">

**Comment by bacongobbler** [comment]
Thanks @Megrax! This project is still a work-in-progress. There are a few UI elements that we need to fix up, including table output.

Thanks for bringing this up!

**Comment by bacongobbler** [comment]
Looks like this has been fixed in #27. Thanks for the report!
