### ISSUE TITLE
Store user theme preference in local storage?

### ISSUE THREAD

**Issue by radu-matei** [fermyon/styleguide#3]
Consider the following scenario:

- I have dark mode set in my browser / OS
- I change the theme on the website to light mode by pressing the button
- I navigate to another page

Whenever I navigate to another page, my theme returns to dark — do we want to store the user preference in local storage?

**Comment by flynnduism** [comment]
Testing that JavaScript, it works perfectly for dark mode > light and dark mode > light. 👏🏻
